INSERT INTO users (name, age) VALUES ("Jake", 20);
INSERT INTO users (name, age) VALUES ("Susan", 22);
INSERT INTO users (name, age) VALUES ("Paul", 21);
INSERT INTO users (name, age) VALUES ("Samantha", 20);
INSERT INTO users (name, age) VALUES ("Old Yeller",5);
INSERT INTO users (name, age) VALUES ("Paul Bunion", 20);
INSERT INTO users (name, age) VALUES ("Megan", 22);
INSERT INTO users (name, age) VALUES ("Ron Weasley", 21);
INSERT INTO users (name, age) VALUES ("Gandalf", 20);
INSERT INTO users (name, age) VALUES ("Bilbo",50);
INSERT INTO users (name, age) VALUES ("Samwise", 20);
INSERT INTO users (name, age) VALUES ("Elmo", 22);
INSERT INTO users (name, age) VALUES ("Bert", 21);
INSERT INTO users (name, age) VALUES ("Big Bird", 20);
INSERT INTO users (name, age) VALUES ("Neo",50);
INSERT INTO users (name, age) VALUES ("Jack", 20);
INSERT INTO users (name, age) VALUES ("Pete", 22);
INSERT INTO users (name, age) VALUES ("Tom", 21);
INSERT INTO users (name, age) VALUES ("Brady", 20);
INSERT INTO users (name, age) VALUES ("Hermit",50);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Armageddon","world-ending event",100.00,"1991-10-02","1997-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Boy Meets Girl","book",5.00,"1993-10-02","1994-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A Scary movie","movie",1000.00,"1995-10-02","1998-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Scariest Movie","movie",10000.00,"1999-10-02","2009-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mister Rogers","TV show",102.00,"1982-10-02","1997-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sesame Street","TV show",103.00,"1983-10-02","1999-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("AA","support group",100.00,"2002-10-02","2005-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Chicxulub","asteroid crater",100.00,"1999-10-02","2002-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("One Fish Two Fish Red Fish Blue Fish","children's book",10.00,"1990-10-02","2000-10-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("la mer","music",105.00,"2002-10-02","2003-10-02");
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.0,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (101.0,2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (102.0,3,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (103.0,4,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (104.0,5,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105.0,6,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (106.0,7,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (107.0,8,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (108.0,9,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (109.0,10,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (110.0,11,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (111.0,12,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (112.0,13,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (113.0,14,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (114.0,15,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (115.0,16,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (116.0,17,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (117.0,18,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (118.0,19,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (119.0,20,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120.0,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (121.0,2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (122.0,3,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123.0,4,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (124.0,5,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125.0,6,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (126.0,7,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (127.0,8,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (128.0,9,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (129.0,10,10);
